server:
  port: ${PORT:50101} #服务端口
spring:
  application:
    name: xc-govern-center #指定服务名
eureka:
  client:
    registerWithEureka: true #服务注册，是否将自己注册到Eureka服务中   1 被其它服务调用时需向Eureka注册
    fetchRegistry: true #服务发现，是否从Eureka中获取注册信息    1 需要从Eureka中查找要调用的目标服务时需要设置为true
    # 1 配置上报Eureka服务地址高可用状态配置对方的地址，单机状态配置自己
    serviceUrl: #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
      defaultZone: ${EUREKA_SERVER:http://eureka02:50102/eureka/}
#      defaultZone: ${EUREKA_SERVER:http://localhost:50102/eureka/}
  server:
    enable-self-preservation: false #是否开启自我保护模式
    # 1 清理失效结点的间隔，在这个时间段内如果没有收到该结点的上报则将结点从服务列表中剔除。
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: ${EUREKA_DOMAIN:eureka01}